### ISSUE TITLE
Remove dependency on libyara, replacing with gyp?

### ISSUE THREAD

**Issue by fproulx-boostsecurity** [chainguard-dev/bincapz#115]
Hello Chainguardians! Love the project. I have another Open Source project, going to be announced next week at OpenSSF conference that I'd like to consider mashing up with bincapz, but I hate the fact that you bring a non Go dependency to `libyara`.

I wonder if it could not be replaced with evaluation of the AST from `gyp` (https://github.com/VirusTotal/gyp) ?

**Comment by tstromberg** [comment]
I, too, would love to eliminate the cgo dependency, but AFAIK, `gyp` only provides a rule parser and emitter; it does not implement a rule evaluator. gyp is, however, an amazing library for automatically updating YARA rules.

I am looking forward to a Rust implementation in the works, which should be callable from go without cgo: https://github.com/VirusTotal/yara-x

**Comment by tstromberg** [comment]
Closing because I believe this to be infeasible today - feel free to reopen if gyp or other libraries include YARA rule evaluation, as having to use libyara from Go sucks.
