### ISSUE TITLE
Remove CRITICAL false positives for popular open-source projects

### ISSUE THREAD

**Issue by tstromberg** [chainguard-dev/bincapz#232]
We're using Wolfi as a benchmark open-source repo. There are a dozen or so CRITICAL false positives that exist, mainly relating to Python code.

- [x] #273 
- [x] #284 
- [x] #285 
- [x] #286 
- [x] #287 
- [x] #288 
- [x] #289 
- [x] #290 
- [x] #291

**Comment by imjasonh** [comment]
> We're using Wolfi as a benchmark open-source repo. There are a dozen or so CRITICAL false positives that exist, mainly relating to Python code.

Is there a list of these somewhere? I'd love to investigate.

**Comment by egibs** [comment]
Linking recent false positive fix PRs for posterity:
- #293
- #297
- #298
- #299
- #300
- #301
- #302
- #303
- #315
- #340
- #352
- #355
- #364
- #365
- #367
- #368
- #369
- #370
- #372
- #375
- #378
- #385

**Comment by egibs** [comment]
Closing this out -- we've resolved most of the outstanding false positives; new false positives are handled as they show up.
