### ISSUE TITLE
GitHub Actions are not allowed to create PRs

### ISSUE THREAD

**Issue by egibs** [chainguard-dev/bincapz#263]
The version bump Workflow is failing (even with `pull-requests: write): https://github.com/chainguard-dev/bincapz/actions/runs/9448914197/job/26023958674#step:8:8

![CleanShot 2024-06-10 at 08 08 34@2x](https://github.com/chainguard-dev/bincapz/assets/20933572/7657ef83-22b9-4369-b3d3-8aba6742faa9)

This is due to these repository settings (and likely controlled at the organization level):
![CleanShot 2024-06-10 at 08 17 43@2x](https://github.com/chainguard-dev/bincapz/assets/20933572/bcb68ff0-eb98-4729-b737-8c998f39ec37)

Turning on `Allow GitHub Actions to create and approve pull requests` will allow the Workflow to create version bump PRs.

Security notes re: turning this on:
- Write access to the repository is required to kick off Workflows via `workflow_dispatch`
- Forks would be able to freely run this against the forked copy of the repository (but not the parent)
- The version bump Workflow does not access or store any sensitive information outside of `${{ github.token }}`
- The version bump Workflow targets a specific file and ensures that the Workflow input is valid
- Automated PRs will still require approval

cc: @tstromberg

**Comment by tstromberg** [comment]
The box is now checked. Thanks for raising this!
