### ISSUE TITLE
awesome-yara Rules

### ISSUE THREAD

**Issue by egibs** [chainguard-dev/bincapz#267]
We've drawn already drawn from several of the rulesets, but I wanted to post the full `awesome-yara` list for easy reference: https://github.com/InQuest/awesome-yara/blob/master/README.md#rules

There are 68 different sources listed of which we've sourced 3-4; though, we've also sourced rules not included on this list -- obviously, not all 68 are relevant but there's an abundance of content here.

**Comment by tstromberg** [comment]
Closing this as we haven't found anything to indicate that it would supply enough accurate coverage to be worth the extra CPU time.
