### ISSUE TITLE
Rename project to "malcontent"

### ISSUE THREAD

**Issue by tstromberg** [chainguard-dev/bincapz#283]
When this project first began, it focused on enumerating binaries' capabilities. It's since grown in two ways:

- We've shifted capability detection to focus on those that may be used maliciously
- We now support scripting languages, not just binaries

Since we're still pre-v1.0, I think it's a good time to consider whether the project's name is still appropriate. I'd like something that references the usage of the program. 

I'm opening the floor to alternative names. The only ones ideas that have come to me so far are `malcapz` and `badcapz`.

Alternatively, maybe we just keep the name as it is. We still have rules in place to detect non-malicious behaviors that could be used for defining `seccomp(2)` profiles, but it's not been fully implemented.

**Comment by tstromberg** [comment]
One other fun ideal: `bintent`

**Comment by egibs** [comment]
I had a few ideas:
- `malcontent` (more of a play on words than the actual definition)
- `scour`
- `binspect`/`bintrospect`

It's hard to find a clever way to use `string` or `text` generically. 😅

**Comment by tstromberg** [comment]
I really like `malcontent`

**Comment by tstromberg** [comment]
![Screenshot from 2024-07-03 18-27-44](https://github.com/chainguard-dev/bincapz/assets/101424/fba16248-778f-4ede-9714-5fa56ef013a0)

**Comment by egibs** [comment]
I tried a more whimsical approach but it doesn't really say "malcontent": 
![_359a137f-5090-4f6b-9713-d8ee50d67309](https://github.com/chainguard-dev/bincapz/assets/20933572/40ad6ce3-8727-4169-b74a-496f007b16cf)

**Comment by tstromberg** [comment]
Here's a rough logo idea - thoughts?

![Image](https://github.com/user-attachments/assets/ff4cb6b7-dda7-434f-9e56-49d2d95c3893)

I was trying to go with a modern, rounded look, but I haven't found exactly what I had in mind. This one is "Typo Round".
