### ISSUE TITLE
Change sorting order from critical to low (discussion)

### ISSUE THREAD

**Issue by ruppde** [chainguard-dev/bincapz#60]
hi,

nice tool. two ideas for it:
1. change the order of the findings from critical to low, because that's the order you want to read them.
2. consider adding these rules: https://github.com/mthcht/ThreatHunting-Keywords-yara-rules

best regards
arnim

**Comment by tstromberg** [comment]
Interestingly, I find that I read terminal output from last to first; as often "first" has scrolled off my window. I think this idea does makes sense though for other output formats, such as `markdown`. 

If you wanted to try your hand at sending in a pull request to modify the order in markdown, it just requires flipping the expression here: https://github.com/chainguard-dev/bincapz/blob/06f81a395335f27c524dc6ed558c63dd7de55edf/pkg/render/markdown.go#L71
