### ISSUE TITLE
yara addfile third_party/yara-rules-full.yar: invalid field name "imphash"

### ISSUE THREAD

**Issue by cipriancraciun** [chainguard-dev/bincapz#63]
I've just compiled the tool as suggested in the README:
~~~~
go install github.com/chainguard-dev/bincapz@latest
~~~~

When running it on `/bin/true` it fails with:
~~~~
> ~/go/bin/bincapz /bin/true 

scanning /bin/true ...
scan failed: YARA rule compilation: walk: yara addfile third_party/yara-rules-full.yar: invalid field name "imphash"
~~~~

I am running OpenSUSE Tumbleweed, with the following packages:
~~~~
> zypper info libyara-devel

Information for package libyara-devel:
--------------------------------------
Repository     : opensuse-oss-distribution
Name           : libyara-devel
Version        : 4.5.0-1.1
Arch           : x86_64
Vendor         : openSUSE
Installed Size : 177.3 KiB
Installed      : Yes
Status         : up-to-date
Source package : yara-4.5.0-1.1.src
~~~~

~~~~
> go version

go version go1.21.7 linux/amd64
~~~~

**Comment by tstromberg** [comment]
That's really interesting! I haven't tested it in OpenSUSE, but have in Arch Linux, which appears to be on yara 4.3.2-1. I'll see about installing a Tumbleweed VM to see what might be going on: my going theory is that 4.5.0 is incompatible with one of these two dependencies:

- https://github.com/hillu/go-yara
- https://github.com/YARAHQ/yara-forge

In the meantime, if you want to try `bincapz`, I think this workaround will work:

`bincapz --third_party=false`

That will disable the YaraFORGE 3rd party rules.

**Comment by tstromberg** [comment]
I'm successfully using bincapz w/ yara v4.5.0 on macOS. I tried to start a Tumbleweed VM but it's not coming up for some reason, so I haven't yet been able to replicate this issue.

**Comment by tstromberg** [comment]
I haven't been able to duplicate this yet - but I wonder if this may be due to a missing OpenSSL dependency: https://github.com/VirusTotal/yara-python/issues/179

**Comment by tstromberg** [comment]
I don't think it will work, but can you try installing the `openssl-devel` package?

My theory is that yara may only enable the `imphash` feature it can find the necessary library support. If it requires compile-time support, installing `openssl-devel` won't help, but if it determines the existence of the dependency at runtime, it should work.


One workaround I thought about is to change this from a fatal error to a warning, but it could mask a loss an unexpected loss in functionality.

**Comment by egibs** [comment]
FWIW, I ran into this when testing #181 inside of a Wolfi container. Installing `openssl-dev` (`apk add openssl-dev`) resolved the error.

**Comment by egibs** [comment]
Cross-posting from the closed PR
---
OpenSSL's libraries are required for Yara (depending on the platform being used).

A non-exhaustive list of Linux distributions and their respectie package names can be found below:

* Debian, Ubuntu
  * `libssl-dev`
* CentOS, Fedora, RHEL, Rocky:
  * `openssl-devel`
* Alpine/Wolfi:
  * `openssl-dev`
* Arch:
  * `openssl` (Arch includes the libraries)
* OpenSUSE:
  * `libopenssl-devel`
