### ISSUE TITLE
`go install` triggers malware detection

### ISSUE THREAD

**Issue by josephlewis42** [chainguard-dev/bincapz#75]
Installing `bincapz` as specified in the README using `go install` causes go to download and save the testdata directory in its mod cache. `testdata` contains samples that trigger malware scanners.

Would it be possible to either distribute binaries,  make it so the samples are obfuscated (e.g. in zip files with the "infected" password or encrypted), or something else to prevent this?

Thanks!

**Comment by tstromberg** [comment]
I think that should be possible - any tip as to what scanner was triggering this?

**Comment by cruiserh** [comment]
The tool uses a scanner developed by ReversingLabs.

**Comment by tstromberg** [comment]
I asked because I've run into something similar with Elastic Defend—but it triggers on the YARA rules rather than the testdata.

I'm open to providing binaries if someone contributes the GitHub actions configuration for doing so.
