### ISSUE TITLE
Have markdown output link each finding to where we can learn more

### ISSUE THREAD

**Issue by mattmoor** [chainguard-dev/bincapz#81]
We have started to use the markdown output in `wolfictl check diff` on PRs, and it would be a fantastic resource for reviewers if each finding linked to resources where they could learn more about the significance of each finding.

ref: https://github.com/wolfi-dev/os/pull/16100

e.g. I'm guessing the symlink resolution finding above is from: https://github.com/chainguard-dev/bincapz/blob/main/rules/fs/symlink-resolve.yara, the IP resolution finding is from: https://github.com/chainguard-dev/bincapz/blob/main/rules/net/ip-resolve.yara, and the code_eval finding is from: https://github.com/chainguard-dev/bincapz/blob/main/rules/techniques/code_eval.yara

Even just linking to these `yara` files would be a help, but really more broadly we have to find a good way of making these findings readily actionable for reviewers.

**Comment by mattmoor** [comment]
cc @tstromberg @jedsalazar

**Comment by tstromberg** [comment]
+1 to this suggestion. This is related in part to what I'd like to do for #62

**Comment by tstromberg** [comment]
Here's what I'm thinking about:

- Host a page with a URL for each rule (either single-file with anchors or multiple files)
- Documentation includes description, diff reviewer guidance, source code to rule, upstream documentation, author, license
- Markdown output links to this documentation
- Start with straight GitHub markdown preview links, but GitHub pages make sense eventually.

**Comment by mattmoor** [comment]
That sounds awesome. 🤩
