### ISSUE TITLE
False positive High `exec()` warning from python string

### ISSUE THREAD

**Issue by mattmoor** [chainguard-dev/bincapz#93]
https://github.com/wolfi-dev/os/pull/16158

diff view: https://github.com/beartype/beartype/compare/v0.17.2...v0.18.0

file: `beartype/_util/hint/pep/proposal/utilpep613.py`

matched diff:
![image](https://github.com/chainguard-dev/bincapz/assets/2442466/08a6debf-895f-43d9-9710-9cb203278db4)

**Comment by mattmoor** [comment]
cc @tstromberg @jedsalazar 

not sure how we want to avoid comments and strings in dynamic languages

**Comment by tstromberg** [comment]
Thanks for the report. I'll have to think about this a little. The easiest
way is probably a language preprocessor that strips comments out before
feeding them to YARA.

YARA rules will never perform as well as an AST parser for finding
dangerous function calls in dynamic languages, but with some creativity on
rule design, it can detect the majority of them.

**Comment by tstromberg** [comment]
This should now show up as a "medium"

We're still not excluding code in strings. That's going to take some work.
