### ISSUE TITLE
`bincapz` flags rust binary for `var/tmp` reference

### ISSUE THREAD

**Issue by mattmoor** [chainguard-dev/bincapz#95]
ref: https://github.com/wolfi-dev/os/pull/16138

Source diff: https://github.com/astral-sh/ruff/compare/v0.3.4...v0.3.5

The string itself looks like something from a test 🤔 
```
var/tmp/dev/shmstrptime_replaceexamplessee
```

What's interesting is that one of the embedded strings is `strptime` which appears to be a Rust `datetime` function that figures prominently in the diff.

I wonder how this ended up in the final binary, but flagging this for later.

**Comment by tstromberg** [comment]
It turns out that `ruff` too tries to detect programs that hardcode this directory - which is why bincapz flags it:

https://github.com/astral-sh/ruff/blob/42d52ebbec275389ee0458a3bf373268278bd51a/crates/ruff_linter/src/rules/flake8_bandit/settings.rs#L8

**Comment by tstromberg** [comment]
Leaving as a true positive, even if rust is merging everything into a long character mess.
