### ISSUE TITLE
Is pkg-config a dependency?

### ISSUE THREAD

**Issue by alcidesmig** [chainguard-dev/bincapz#99]
[alcides@mig] ~ $ GO111MODULE=on go install github.com/chainguard-dev/bincapz@latest
github.com/hillu/go-yara/v4: exec: "pkg-config": executable file not found in $PATH

System:

OS: Arch Linux x86_64
Kernel: 6.6.23-1-lts
yara 4.5.0-1
go version go1.22.1 linux/amd64

**Comment by tstromberg** [comment]
I didn't realize it, but yes, `pkg-config` appears to be an indirect dependency for most users according to https://github.com/hillu/go-yara

> On Unix-like systems, libyara version 4.3, corresponding header files, and pkg-config must be installed. Adding go-yara v4 to a project with Go Modules enabled, simply add the proper dependency…

**Comment by tstromberg** [comment]
Closing, as the answer is, unfortunately, yes.
